[tool.isort]
multi_line_output=3
force_grid_wrap=0
line_length=70
use_parentheses='True'
include_trailing_comma='True'
skip=['.venv','python_package']
src_paths = ["dags"]

[tool.black]
line-length = 120
target-version = ['py36', 'py37', 'py38']
exclude = '''
/(
    \.eggs
  | \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | _build
  | buck-out
  | build
  | dist
  | tests_data
  | __pycache__
  | notebooks
  | examples
)/
'''